### ISSUE TITLE
[Deployment] Github Action 초기 설정

### ISSUE THREAD

**Issue by hoonii2** [hoonii2/githubaction_codedeploy#1]
## Description

- Github Action / AWS S3 연동

## Tasks

- [x] Spring Boot 초기 설정 및 간단한 RestController 설정
- [x] Github Action
- [x] workflow 스크립트 작성
- [x] workflow 실행
- [x] S3 생성
- [x] IAM 권한 설정
- [x] S3 에 jar 업로드
