### ISSUE TITLE
[Deployment] EC2 & CodeDeploy 설정

### ISSUE THREAD

**Issue by hoonii2** [hoonii2/githubaction_codedeploy#2]
## Description

- EC2 & CodeDeploy 설정

## Tasks

- [x] VPC & Subnet 생성
- [x] EC2 생성 및 기본 설정
- [x] EC2 CodeDeploy Agent 설치
- [x] EC2 IAM Role 부여
- [x] CodeDeploy IAM Role 생성 및 부여
- [x] CodeDeploy 스크립트 작성 및 테스트
