### ISSUE TITLE
[Deployment] EC2 & RDS

### ISSUE THREAD

**Issue by hoonii2** [hoonii2/githubaction_codedeploy#3]
## Description

- EC2 & RDS 배포

## Tasks

- [x] DB Subnet Group 생성
- [x] RDS Security Group 설정
- [x] RDS 배포 ( Private Subnet )
- [x] EC2 - RDS 접속 확인
- [ ] Spring Boot JDBC 연결
